version: '3'
services:
  website:
    build: .
    ports:
      - "80:5000"
    networks:
      - frontend
    volumes:
      - .:/code
    depends_on:
      - redisdb
    environment:
      - REDIS_HOST=redisdb
      - REDIS_PORT=6379
      - FLASK_ENV=development
  redisdb:
    image: "redis:alpine"
    ports:
      - "6379"
    networks:
      - frontend
    volumes:
      - data:/data
networks:
  frontend:
volumes: 
  data: